apiVersion: v1
kind: Pod
metadata:
  name: mypod-0
  labels:
    run: mypod
spec:
  schedulerName: dj-scheduler
  restartPolicy: Never
  containers:
  - command:
    - "sleep"
    - "5s"
    image: busybox:latest
    name: sleep
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod-1
  labels:
    run: mypod
spec:
  schedulerName: dj-scheduler
  restartPolicy: Never
  containers:
  - command:
    - "sleep"
    - "5s"
    image: busybox:latest
    name: sleep
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi

---

apiVersion: v1
kind: Pod
metadata:
  name: mypod-2
  labels:
    run: mypod
spec:
  schedulerName: dj-scheduler
  restartPolicy: Never
  containers:
  - command:
    - "sleep"
    - "5s"
    image: busybox:latest
    name: sleep
    resources:
      limits:
        cpu: 50m
        memory: 50Mi
      requests:
        cpu: 50m
        memory: 50Mi
