apiVersion: v1
kind: ServiceAccount
metadata:
  name: dj-scheduler

---

kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dj-scheduler
rules:
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - create

- apiGroups:
  - ""
  resources:
  - nodes
  verbs:
  - list
  - get

- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - get

- apiGroups:
  - ""
  resources:
  - pods/binding
  verbs:
  - create
  - list
  - get


---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dj-scheduler-cluster
subjects:
- kind: ServiceAccount
  name: dj-scheduler
  namespace: dj-scheduler
roleRef:
  kind: ClusterRole
  name: dj-scheduler
  apiGroup: rbac.authorization.k8s.io
